### ISSUE TITLE
feature: jump to next/previous error marker

### ISSUE THREAD

**Issue by catull** [tsoding/cm#154]
The combined stdout and stderr is collected into a "buffer".

The cursor keys allow for a line-by-line navigation.

It would be great if a certain key combination would navigate from error marker to the next.
It would also be great to navigate backwards, from error marker to the previous one.

This feature reduces the key strokes.

**Comment by rexim** [comment]
@catull we already have that. Use <kbd>Alt</kbd>+<kbd>j</kbd> and <kbd>Alt</kbd>+<kbd>k</kbd> to jump between the matches. See [Default Shortcuts](https://github.com/tsoding/cm/tree/84aad6d68e96c2eea797a301412d811213beb4b1#default-shortcuts) for more information.
