### ISSUE TITLE
more gradual scrolling

### ISSUE THREAD

**Issue by travisstaloch** [tsoding/cm#212]
Scrolling up/down only happens a page at a time and makes reading awkward at times, especially when paging through large outputs.  I wish cm would scroll more gradually like my terminal (in smaller increments).  

Not sure if these are applicable, i started looking into how to implement this:
- https://docs.rs/ncursesw/0.5.1/ncursesw/?search=scroll
- https://www.mkssoftware.com/docs/man3/curs_scroll.3.asp

**Comment by rexim** [comment]
@travisstaloch I tried to address this issue in #219. Please check out the latest commit and close this issue if it works for you.

**Comment by travisstaloch** [comment]
Looks good to me! :smile: Much easier to read now. Thanks so much!
