### ISSUE TITLE
endwin() on Enter in OutputBuffer looks like a total hack and it's unclear why it even works

### ISSUE THREAD

**Issue by rexim** [tsoding/cm#47]
introduced in #46

**Comment by et342** [comment]
According to https://invisible-island.net/ncurses/man/curs_initscr.3x.html#h3-endwin, this is how `endwin` is supposed to be used.
> <..>
> A program should always call endwin before exiting or escaping from curses mode temporarily.
> <..>
> Calling [refresh(3x)](https://invisible-island.net/ncurses/man/curs_refresh.3x.html) or [doupdate(3x)](https://invisible-island.net/ncurses/man/curs_refresh.3x.html) after a temporary escape causes the program to resume visual mode.

**Comment by rexim** [comment]
@et342 oh, thank you so much for finding this! :+1:
